.TH GAMEOFLIFE 6 "December 26, 2021"
.SH NAME
gameoflife \- simple implementation of conway's game of life.
.SH SYNOPSIS
\fBgameoflife\fP [ -hGr ] \fISAVEGAME\fP
.SH KEYBINDINGS
The default keybindings are zoom in(+), zoom out(-), move left (h), 
move down(j), move up (k), move right (l), quit (q), save game (s).
